apiVersion: apps/v1
kind: Deployment
metadata:
  name: tui-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tui-backend
  template:
    metadata:
      labels:
        app: tui-backend
    spec:
      containers:
        - name: backend
          image: asia.gcr.io/rchin-project-32261/tui-backend:TAG_PLACEHOLDER
          ports:
            - containerPort: 3000
          env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: production
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: uri
      imagePullSecrets:
      - name: gcr-json-key