apiVersion: apps/v1
kind: Deployment
metadata:
  name: tui-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tui-frontend
  template:
    metadata:
      labels:
        app: tui-frontend
    spec:
      containers:
      - name: frontend
        image: asia.gcr.io/rchin-project-32261/tui-frontend:TAG_PLACEHOLDER
        ports:
        - containerPort: 8080 # The port Nginx within the container is listening on.
      imagePullSecrets:
      - name: gcr-json-key
