apiVersion: v1
kind: Service
metadata:
  name: tui-frontend
spec:
  selector:
    app: tui-frontend
  ports:
  - protocol: TCP
    port: 80  # The port the service is exposed on.
    targetPort: 8080  # The container port Nginx is listening on.
  type: LoadBalancer
